@Project.WebApi_HostAddress = https://localhost:7198

###

GET {{Project.WebApi_HostAddress}}/api/about

###

POST {{Project.WebApi_HostAddress}}/api/about
Content-Type: application/json

{
  //CreateAboutCommand
}

###
